version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\MicTools
image:
- Visual Studio 2017
configuration:
- Release
platform:
- x64
environment:
  matrix:
  - arch: Win64
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build64
    cd build64
    cmake --version
    cmake -G %generator% ..
build:
  project: c:\projects\MicTools\build64\MicTools.sln
  verbosity: minimal
  parallel: true
only_commits:
  files:
    - CMakeLists.txt
    - appveyor.yml
    - impl/
    - resources/
